apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: mfpocns
spec:
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: pvc-nfs-data    
      containers:
      - name: mongod-pod
        image: mongo
        ports:
          - containerPort: 27017
        volumeMounts:
        - name: data
          mountPath: /data/db
