apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs-data
  namespace: mfpocns
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 3Gi
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.1.91
    path: "/mnt/sharedfolder/mongo"
