apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: mfpocns
spec:
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
#      securityContext:
#        runAsUser: 1000
#        runAsGroup: 1000
#        fsGroup: 1000
#        fsGroupChangePolicy: "OnRootMismatch"
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: pvc-nfs-data
#      initContainers:
#      - name: chmod-er
#        image: busybox:latest
#        securityContext:
#          runAsUser: 1000
#        command:
#        - /bin/chown
#        - -R
#        - "1000"
#        - /data/db
#        volumeMounts:
#        - name: data    
#          mountPath: /data/db
      containers:
      - name: mongod-pod
        image: mongo
        securityContext:
          privileged: true
#          runAsUser: 1000
        ports:
          - containerPort: 27017
        volumeMounts:
        - name: data
          mountPath: /data/db
